/* ============================================================
   MANA COFFEE HOUSE — Data Service (Backend Integrated)
   Uses fetch to communicate with the Express API
   ============================================================ */

const DataService = {
  API_URL: 'http://localhost:3000/api',
  _listeners: {},
  _channel: null,

  /* ── Initialization ── */
  init() {
    // Set up BroadcastChannel for cross-tab real-time sync
    try {
      this._channel = new BroadcastChannel('mana_sales_channel');
      this._channel.onmessage = (event) => {
        if (event.data && event.data.type === 'NEW_SALE') {
          this._emit('sale:new', event.data.order);
          this._emit('sales:updated');
        }
      };
    } catch (e) {
      console.warn("BroadcastChannel not supported.");
    }
  },

  /* ── Event System ── */
  on(event, callback) {
    if (!this._listeners[event]) this._listeners[event] = [];
    this._listeners[event].push(callback);
  },

  off(event, callback) {
    if (!this._listeners[event]) return;
    this._listeners[event] = this._listeners[event].filter(cb => cb !== callback);
  },

  _emit(event, data) {
    if (!this._listeners[event]) return;
    this._listeners[event].forEach(cb => cb(data));
  },

  /* ── API Calls ── */
  async getAllOrders() {
    try {
      const res = await fetch(`${this.API_URL}/orders`);
      return await res.json();
    } catch (e) {
      console.error('Error fetching orders', e);
      return [];
    }
  },

  _getDateRangeForFilter(filter) {
    const d = new Date();
    let currentPrefix = '';
    let prevPrefix = '';

    const format = (date, len) => date.toISOString().substring(0, len);

    if (filter === 'today') {
      currentPrefix = format(d, 10);
      d.setDate(d.getDate() - 1);
      prevPrefix = format(d, 10);
    } else if (filter === 'yesterday') {
      d.setDate(d.getDate() - 1);
      currentPrefix = format(d, 10);
      d.setDate(d.getDate() - 1);
      prevPrefix = format(d, 10);
    } else if (filter === 'month') {
      currentPrefix = format(d, 7);
      d.setMonth(d.getMonth() - 1);
      prevPrefix = format(d, 7);
    } else if (filter === 'year') {
      currentPrefix = format(d, 4);
      d.setFullYear(d.getFullYear() - 1);
      prevPrefix = format(d, 4);
    } else {
      currentPrefix = format(d, 10);
      d.setDate(d.getDate() - 1);
      prevPrefix = format(d, 10);
    }
    return { currentPrefix, prevPrefix };
  },

  async getOrdersByPrefix(prefix) {
    try {
      const res = await fetch(`${this.API_URL}/orders?date=${prefix}`);
      return await res.json();
    } catch (e) {
      console.error('Error fetching orders by prefix', e);
      return [];
    }
  },

  async getTodayOrders() {
    const today = Utils.getTodayISO().split('T')[0];
    return this.getOrdersByPrefix(today);
  },

  async getTodayOrderCount(shopIdFilter = 'all') {
    const orders = await this.getTodayOrders();
    if (shopIdFilter && shopIdFilter !== 'all') {
      return orders.filter(o => o.shopId === shopIdFilter).length;
    }
    return orders.length;
  },

  async saveOrder(order) {
    // Generate IDs if not present (though they should be generated by POS)
    if (!order.orderId) order.orderId = Utils.generateId('ORD');
    if (!order.billNumber) {
        const count = await this.getTodayOrderCount();
        order.billNumber = Utils.generateBillNumber(count);
    }
    order.timestamp = new Date().toISOString();
    order.status = 'completed';

    try {
      const res = await fetch(`${this.API_URL}/orders`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(order)
      });
      const data = await res.json();

      if (data.success) {
        // Emit events for same-tab listeners
        this._emit('sale:new', order);
        this._emit('sales:updated');

        // Broadcast to OTHER tabs (dashboard) via BroadcastChannel
        if (this._channel) {
          this._channel.postMessage({ type: 'NEW_SALE', order });
        }
        return order;
      } else {
          console.error("Failed to save order", data.error);
          return null;
      }
    } catch (e) {
      console.error("API error saving order", e);
      return null;
    }
  },

  /* ── Analytics ── */
  async getDashboardData(shopIdFilter = 'all', timeFilter = 'today') {
    const { currentPrefix, prevPrefix } = this._getDateRangeForFilter(timeFilter);
    let currentOrders = await this.getOrdersByPrefix(currentPrefix);
    let prevOrders = await this.getOrdersByPrefix(prevPrefix);

    if (shopIdFilter && shopIdFilter !== 'all') {
      currentOrders = currentOrders.filter(o => o.shopId === shopIdFilter);
      prevOrders = prevOrders.filter(o => o.shopId === shopIdFilter);
    }

    const totalRevenue = currentOrders.reduce((sum, o) => sum + o.totalAmount, 0);
    const totalOrders = currentOrders.length;
    const avgOrderValue = totalOrders > 0 ? totalRevenue / totalOrders : 0;

    // Previous data for REAL % change
    const prevRevenue = prevOrders.reduce((sum, o) => sum + o.totalAmount, 0);
    const prevOrderCount = prevOrders.length;
    const prevAOV = prevOrderCount > 0 ? prevRevenue / prevOrderCount : 0;

    const revenueChange = Utils.percentChange(totalRevenue, prevRevenue);
    const ordersChange = Utils.percentChange(totalOrders, prevOrderCount);
    const aovChange = Utils.percentChange(avgOrderValue, prevAOV);

    const shopsToProcess = (shopIdFilter && shopIdFilter !== 'all') 
      ? SHOPS.filter(s => s.id === shopIdFilter) 
      : SHOPS;

    // Sales by area
    const salesByArea = {};
    shopsToProcess.forEach(shop => {
      const shopOrders = currentOrders.filter(o => o.shopId === shop.id);
      salesByArea[shop.name] = shopOrders.reduce((sum, o) => sum + o.totalAmount, 0);
    });

    // Best area
    let bestArea = { name: 'N/A', revenue: 0 };
    Object.entries(salesByArea).forEach(([name, rev]) => {
      if (rev > bestArea.revenue) bestArea = { name, revenue: rev };
    });

    // Popular items
    const itemCounts = {};
    currentOrders.forEach(o => {
      (o.items || []).forEach(item => {
        if (!itemCounts[item.name]) itemCounts[item.name] = 0;
        itemCounts[item.name] += item.quantity;
      });
    });
    const popularItems = Object.entries(itemCounts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 6)
      .map(([name, count]) => ({ name, count }));

    // Hourly trend
    const hourlyRevenue = new Array(24).fill(0);
    currentOrders.forEach(o => {
      const hour = Utils.getHour(o.timestamp);
      hourlyRevenue[hour] += o.totalAmount;
    });

    // Target achievement
    const targetAchievement = {};
    shopsToProcess.forEach(shop => {
      const shopRevenue = salesByArea[shop.name] || 0;
      targetAchievement[shop.name] = {
        revenue: shopRevenue,
        target: shop.targetDaily,
        percentage: Math.min(100, Math.round((shopRevenue / shop.targetDaily) * 100))
      };
    });

    // Recent sales (last 20)
    const recentSales = currentOrders
      .sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp))
      .slice(0, 20)
      .map(o => ({
        orderId: o.orderId,
        time: Utils.formatTime(o.timestamp),
        shopName: SHOPS.find(s => s.id === o.shopId)?.name || o.shopId,
        customerName: o.customerName,
        totalAmount: o.totalAmount,
        itemCount: (o.items || []).reduce((sum, i) => sum + i.quantity, 0),
        itemsSummary: (o.items || []).map(i => `${i.name} (${i.quantity})`).join(', '),
        billNumber: o.billNumber
      }));

    return {
      kpis: {
        totalRevenue,
        totalOrders,
        avgOrderValue,
        bestArea,
        revenueChange,
        ordersChange,
        aovChange,
      },
      salesByArea,
      popularItems,
      hourlyRevenue,
      targetAchievement,
      recentSales,
    };
  },

  async getExportData() {
    const todayOrders = await this.getTodayOrders();
    return todayOrders.map(o => ({
      'Bill Number': o.billNumber,
      'Date': Utils.formatDate(o.timestamp),
      'Time': Utils.formatTime(o.timestamp),
      'Shop': SHOPS.find(s => s.id === o.shopId)?.name || o.shopId,
      'Customer': o.customerName,
      'Phone': o.customerPhone || '',
      'Items': (o.items || []).map(i => `${i.name} x${i.quantity}`).join('; '),
      'Subtotal': o.subtotal,
      'Tax': o.tax,
      'Discount': o.discount || 0,
      'Total': o.totalAmount,
      'Salesperson': o.salespersonName || '',
    }));
  },

  /* ── Reset data ── */
  async resetData() {
    try {
        await fetch(`${this.API_URL}/reset`, { method: 'POST' });
        this._emit('sales:updated');
        if (this._channel) {
            this._channel.postMessage({ type: 'NEW_SALE', order: null });
        }
    } catch(e) {
        console.error("Error resetting data", e);
    }
  }
};
